dtb-$(CONFIG_ARCH_P660)		+= hisi_p660_evb.dtb hip05-d02.dtb hip05-2p1s.dtb hip05-lemon.dtb hip05-s01.dtb
dtb-$(CONFIG_ARCH_Hi1610)	+= hi1610_16c-evb.dtb hi1610_32c-evb.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
